"""
tools/search.py

Search and retrieval utilities for the Bluesky Post Explainer.

This module supports:
1. DuckDuckGo search via DDGS
2. Lightweight result filtering
3. External URL fetching
4. LLM-ready context formatting
"""

import logging
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import List, Optional

import httpx
from ddgs import DDGS


### ---------------------------------------------------------------------------
### Logging
### ---------------------------------------------------------------------------

logger = logging.getLogger(__name__)


### ---------------------------------------------------------------------------
### Data model
### ---------------------------------------------------------------------------

@dataclass
class SearchResult:
    """
    Normalized search result used by the explainer.
    """

    query: str
    title: str
    url: str
    snippet: str


### ---------------------------------------------------------------------------
### HTTP configuration
### ---------------------------------------------------------------------------

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}


### ---------------------------------------------------------------------------
### Utility helpers
### ---------------------------------------------------------------------------

def get_timestamp() -> str:
    """
    Return a timezone-aware UTC timestamp.
    """

    return datetime.now(UTC).isoformat()


def _clean_text(text: str) -> str:
    """
    Normalize snippets/titles for cleaner LLM context.
    """

    return (text or "").strip().replace("\n", " ")


def _query_terms(query: str) -> List[str]:
    """
    Extract useful query terms for lightweight relevance filtering.
    Removes quotes and ignores very short words.
    """

    cleaned_query = query.replace('"', "")
    return [
        word.lower()
        for word in cleaned_query.split()
        if len(word) > 4
    ]


### ---------------------------------------------------------------------------
### Query refinement
### ---------------------------------------------------------------------------

def refine_query(query: str) -> str:
    """
    Improve query precision.

    If the query is a multi-word phrase, wrap it in quotes.
    This helps avoid broad matches such as "Ralph Lauren" for
    "Ralph Wiggum technique".
    """

    query = query.strip()

    if not query:
        return query

    if '"' in query:
        return query

    words = query.split()

    if len(words) >= 3:
        return f'"{query}"'

    return query


### ---------------------------------------------------------------------------
### Relevance filtering
### ---------------------------------------------------------------------------

def is_relevant(result: SearchResult, query: str) -> bool:
    """
    Lightweight filter to remove obviously unrelated results.

    It keeps a result if at least one important query term appears
    in the result title or snippet.
    """

    text = f"{result.title} {result.snippet}".lower()
    terms = _query_terms(query)

    if not terms:
        return True

    return any(term in text for term in terms)


### ---------------------------------------------------------------------------
### Core search
### ---------------------------------------------------------------------------

def search(
    queries: List[str],
    max_results_per_query: int = 3,
    max_total_results: int = 5,
) -> List[SearchResult]:
    """
    Run each query independently and return deduplicated search results.

    Args:
        queries: Search queries generated by the planner.
        max_results_per_query: Results requested per query.
        max_total_results: Global result cap.

    Returns:
        List of normalized SearchResult objects.
    """

    results: List[SearchResult] = []
    seen_urls = set()

    with DDGS() as ddgs:
        for query in queries:
            refined_query = refine_query(query)

            if not refined_query:
                continue

            try:
                hits = ddgs.text(
                    refined_query,
                    max_results=max_results_per_query,
                )

                for hit in hits:
                    url = hit.get("href", "")

                    if not url or url in seen_urls:
                        continue

                    result = SearchResult(
                        query=query,
                        title=_clean_text(hit.get("title", "")),
                        url=url,
                        snippet=_clean_text(hit.get("body", "")),
                    )

                    if not is_relevant(result, query):
                        continue

                    seen_urls.add(url)
                    results.append(result)

                    if len(results) >= max_total_results:
                        return results

            except Exception as exc:
                logger.debug("[search] query failed: %s | %s", query, exc)

    return results


### ---------------------------------------------------------------------------
### External URL fetch
### ---------------------------------------------------------------------------

def fetch_url_content(
    url: str,
    max_chars: int = 5000,
    timeout: int = 10,
) -> str:
    """
    Fetch raw HTML/text content from an external URL.

    This is intentionally lightweight. The final LLM receives only
    the first max_chars characters.
    """

    if not url:
        return ""

    try:
        response = httpx.get(
            url,
            timeout=timeout,
            headers=HEADERS,
            follow_redirects=True,
        )
        response.raise_for_status()

        return response.text[:max_chars]

    except httpx.HTTPStatusError as exc:
        logger.debug(
            "[fetch_url_content] HTTP %s for %s",
            exc.response.status_code,
            url,
        )
        return ""

    except Exception as exc:
        logger.debug("[fetch_url_content] failed for %s | %s", url, exc)
        return ""


### ---------------------------------------------------------------------------
### Context formatting
### ---------------------------------------------------------------------------

def as_context_block(results: List[SearchResult]) -> str:
    """
    Format search results into an LLM-ready context block.
    Results are grouped by query to preserve retrieval intent.
    """

    if not results:
        return "No relevant external context found."

    lines: List[str] = []
    current_query: Optional[str] = None

    for result in results:
        if result.query != current_query:
            current_query = result.query
            lines.append(f"\n### Query: {current_query}")

        lines.append(f"- {result.title}")
        lines.append(f"  {result.snippet}")
        lines.append(f"  {result.url}")

    return "\n".join(lines).strip()


### ---------------------------------------------------------------------------
### Unified retrieval interface
### ---------------------------------------------------------------------------

def retrieve_context(
    needs_search: bool,
    queries: List[str],
    external_url: Optional[str] = None,
) -> str:
    """
    Main retrieval entrypoint.

    Priority:
    1. Fetch external URL directly if available
    2. Use search queries if search is needed
    3. Return no-context message otherwise
    """

    ##### Priority 1: direct external source
    if external_url:
        content = fetch_url_content(external_url)

        if content:
            return f"### External Source\n{external_url}\n\n{content[:2000]}"

        logger.debug("[retrieve_context] external fetch failed; falling back to search")

    ##### Priority 2: search
    if needs_search and queries:
        return as_context_block(search(queries))

    return "No additional context needed."


### ---------------------------------------------------------------------------
### Local smoke test
### ---------------------------------------------------------------------------

if __name__ == "__main__":
    test_queries = [
        "Ralph Wiggum technique explanation",
        "Ralph Wiggum technique reddit",
    ]

    print("Timestamp:", get_timestamp())

    search_results = search(test_queries)

    print(f"\nResults: {len(search_results)}\n")
    print(as_context_block(search_results))